@startuml
allow_mixing

interface equations
interface observer
interface lorenz
interface euler
interface integrator
interface rk
node main

main -down-> equations
main -down-> observer
equations -down-> lorenz
main -down-> integrator
integrator -down-> euler
integrator -down-> rk

interface equations {
    +get_system_size()
    +set_initial_state(s)
    +f(t, s)
}

interface observer {
 +observer_init()
 +observer_write()
 +observer_finalize()
}

interface integrator {
    + dt
    + n
    + type
}


@enduml