@startuml

allow_mixing

interface solver
interface equations
interface integrator
interface observer
interface system

interface solver {
    +init()
    +solve()
}

interface equations {
    +get_system_size()
    +set_initial_state(s)
    +f(t, s)
}

interface integrator {
    +integrator(t, s)
}

interface system {
    +system(t, s)
}

interface observer {
    +init()
    +write()
    +finalize()
}



@enduml
